title = "Christian Coppoletti - Portfolio"
baseURL = 'https://coppoletti.co/'
languageCode = 'en-us'

[params]
  favicon = "/favicon.ico"

[taxonomies]
category = "categories"

[menus]
[[menus.main]]
    name = 'Work'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Bio'
    pageRef = '/bio'
    weight = 20
[[menus.main]]
    name = 'Resume'
    url = '/downloads/christian-coppoletti-resume.pdf'
    weight = 30
[[menus.main]]
    name = 'Contact'
    url = '#contact-popup'
    weight = 40
[[menus.work]]
    name = 'Game Dev'
    pageRef = '/work/gamedevelopment'
    weight = 10
[[menus.work]]
    name = 'Industrial Design'
    pageRef = '/work/industrialdesign'
    weight = 20
[[menus.work]]
    name = 'Pipelines'
    pageRef = '/work/pipelines'
    weight = 30
[[menus.work]]
    name = 'Artwork'
    pageRef = '/work/artwork'
    weight = 40

