title = "Website Name"
baseURL = 'https://example.org'
languageCode = 'en-us'

[params]
  # "relatedtext" is the text that appears above the tag list at the bottom of pages.
  relatedtext = "Related"
  favicon = "/favicon.ico"

[taxonomies]
category = "categories"

[menus]
[[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
[[menus.main]]
    name = 'Work'
    pageRef = '/'
    weight = 20
[[menus.main]]
    name = 'Bio'
    pageRef = '/bio'
    weight = 30
[[menus.main]]
    name = 'Resume'
    pageRef = '/downloads/christian-coppoletti-resume.pdf'
    weight = 40
[[menus.work]]
    name = 'Pipelines'
    pageRef = '/work/pipelines'
    weight = 10
[[menus.work]]
    name = 'Mobile Apps'
    pageRef = '/work/mobileapps'
    weight = 20
[[menus.work]]
    name = 'Artwork'
    pageRef = '/work/artwork'
    weight = 30
[[menus.work]]
    name = 'Industrial Design'
    pageRef = '/work/industrialdesign'
    weight = 20
[[menus.work]]
    name = 'Custom Plugins'
    pageRef = '/work/customplugins'
    weight = 20
[[menus.work]]
    name = 'Game Dev'
    pageRef = '/work/gamedevelopment'
    weight = 20