name: Christian Coppoletti
title: Coppoletti
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]

sass:
  style: compressed

navigation:
 - text: BIO
   url: /bio/
 - text: CONTACT
   url: /contact/
 - text: PORTFOLIO
   url: /
 - text: BLOG
   url: /blog/

collections:
  3DArt:
  graphic:
  games:
  2DArt:
  Zenimax:
